from fpdf import FPDF
import tempfile
from datetime import datetime

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'PCOS & Anemia Risk Assessment Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_report(condition, inputs, probability, risk_level):
    pdf = PDFReport()
    pdf.add_page()
    
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1)
    pdf.cell(0, 10, f"Assessment Type: {condition.upper()}", 0, 1)
    pdf.ln(5)
    
    pdf.set_font('Arial', 'B', 14)
    if risk_level == "Elevated":
        pdf.set_text_color(220, 38, 38)
    elif risk_level == "Moderate":
        pdf.set_text_color(217, 119, 6)
    else:
        pdf.set_text_color(22, 163, 74)
        
    pdf.cell(0, 10, f"Risk Level: {risk_level}", 0, 1)
    pdf.cell(0, 10, f"Calculated AI Probability: {probability * 100:.1f}%", 0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Provided Inputs:", 0, 1)
    pdf.set_font('Arial', '', 11)
    for k, v in inputs.items():
        pdf.cell(0, 8, f"{k.replace('_', ' ').title()}: {v}", 0, 1)
        
    pdf.ln(15)
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 8, "Disclaimer: This report is generated by an AI research prototype and is NOT a medical diagnosis. Please consult a qualified healthcare provider for proper clinical evaluation.")
    
    temp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    pdf.output(temp.name)
    return temp.name
